### ISSUE TITLE
register two nodered instances

### ISSUE THREAD

**Issue by xjustbmw** [joaomgcd/node-red-contrib-join-joaoapps#13]
I have two nodered servers on different local ips, same public network.
They seem to be getting the same device ID when trying to register them to receive messages. 
Each time the second nodered update the other one.

deviceId already existed. Updated existing device

Any way to avoid that ?

**Comment by joaomgcd** [comment]
Unfortunately that's a known limitation for now, sorry. The problem is that the device ID is its public IP, so you'll only be able to use 1 per public IP. Sorry!
