### ISSUE TITLE
fix so latest version turns up in palette

### ISSUE THREAD

**Issue by strelniece** [joaomgcd/node-red-contrib-join-joaoapps#16]
hi,

is it possible to fix so the latest version will turn up in the palette?

I use NR in my homeassistant so can't use npm.

I need my join-nodes!!! ;)

**Comment by strelniece** [comment]
Well, I managed to get 1.2.3 installed by a worst practice trick...

So now it does work, although it keeps getting an error "couldn't sent push" despite sending...

So hope the update will turn up soon so I can do a more prorper installation and see if that solves it.

**Comment by strelniece** [comment]
And now it turned up, Thanks till whoever did it!

**Comment by joaomgcd** [comment]
Awesome! Glad it finally did! :)
