### ISSUE TITLE
replace already created notification

### ISSUE THREAD

**Issue by bednim** [joaomgcd/node-red-contrib-join-joaoapps#21]
hi, I can't seem to find this in API - but this is the scenario:

I have created notification with JOIN in node-red.

Now I want to replace it with new one - how?

tried TAG option - but that doesn't work.

thanks!

**Comment by joaomgcd** [comment]
You can do that by specifying the **notificationId** field. Hope this helps!

**Comment by bednim** [comment]
thank you - is there a resource I could see all of those fields? looked in docs but could not locate it. thanks!

**Comment by joaomgcd** [comment]
There were indeed some fields missing, but I think I added them all now :)

Check here: https://joaoapps.com/join/api/

**Comment by bednim** [comment]
thanks fab!
