### ISSUE TITLE
node crashes node-red

### ISSUE THREAD

**Issue by liv-in-sky** [joaomgcd/node-red-contrib-join-joaoapps#4]
dear joao -I have the following problem - I added this already to google+ but I think it is better here !

I''m using iobroker (smarthome node software which is having node-red as adapter) and I  installed the join node (node-red-contrib-join-joaoapps)- now I get the following error and node-red isn't starting anymore

node-red.0	2018-07-27 12:30:28.507	debug	27 Jul 12:30:28 - Error: listen EADDRINUSE :::1825 at Object._errnoException (util.js:992:11) at _exceptionWithHostPort (util.js:1014:20) at Server.setupListenHandle [as _listen2] (net.js:
node-red.0	2018-07-27 12:30:28.501	debug	27 Jul 12:30:28 - [red] Uncaught Exception:
node-red.0	2018-07-27 12:30:28.486	debug	27 Jul 12:30:28 - [info] Started flows
node-red.0	2018-07-27 12:30:28.267	debug	27 Jul 12:30:28 - [info] [join-server:96c239cd.35d408] Starting server on port 1825...
node-red.0	2018-07-27 12:30:28.238	debug	27 Jul 12:30:28 - [info] [join-server:deb43e1d.7db4a] Starting server on port 1825...
node-red.0	2018-07-27 12:30:27.850	debug	27 Jul 12:30:27 - [info] Starting flows

could you please help me - is it possible to delete the setting of the join-servers somewhere in a json file -

**Comment by joaomgcd** [comment]
Seems like you added 2 servers for Join using the same port? Can that be it?

**Comment by liv-in-sky** [comment]
yes - you right - suddenly I had prblems to receive the join server via ifttt-webhooks . try to solve it I made a new server and tried to add the api-number.  then problem !
do you know how I can delete it with terminal

**Comment by liv-in-sky** [comment]
I changed the config.js file from enanbled true to false - now node-red is starting again

how I can delete the servers in order to define ONE new server?

(I don't really know what I'm doing)


node-red-contrib-join-joaoapps": {
   "name": "node-red-contrib-join-joaoapps",
   "version": "1.1.1",
   "local": true,
   "nodes": {
    "join-config": {
     "name": "join-config",
     "types": [
      "join-config"
     ],
     "enabled": false,
     "local": true,

**Comment by joaomgcd** [comment]
If you enable it again you get the same error, correct?

**Comment by liv-in-sky** [comment]
hi joao,

I made it - after changing the config.js entry  to false - it was possible to open webinterface again - I was able to delete the servers . then enabled again and create a new server - it is able to communicate.

the only problem is: I get the following error everytime I restart node-red

_Credentials could not be decrypted
The flow credential file is encrypted, but the project's encryption key is missing or invalid.
The flow credential file will be reset on the next deployment. Any existing flow credentials will be cleared._


BUT this is  not  a joaoapps problem - it is the node-red adapter for iobroker ! please close this issue.
thanx for answering my questions so fast - have a nice weekend

armin

thanx in any case armin

**Comment by liv-in-sky** [comment]
hey joao - sorry to disturb you again,

node ed is running and also the pushes with join went thru
the problem - each time I restart nodered I have to put in the api key again in the joinserver setting - after I did this I can use it again

do you have some hints for me

**Comment by joaomgcd** [comment]
Does that make node-red not even start? Are you not able to delete those nodes?

**Comment by liv-in-sky** [comment]
hey

sometimes nodered is crashing - sometimes - flows are not startet - after new installation

the problem is that I have to delete everything from the filesystem to get node-red running again - only when I import my old flows. the nodes joinserver and join-config are somewhere hided.
only if I import the flows (in order to overtake other nodes) WITHOUT DEPLOY !!!! - the systems starts to crash after I restart nodered.

at the moment it is working  - I installed nodered on another test system and imported my old flows there- delete all nodes from join and exported all other nodes in my running system

the problem is, that the setting for your node is not dissapearing even I uninstall your node and delete everthing I find in the filesystem. joinserver is hided somewhere in the node setting.

some ideas:
- is it possible that delete an joinserver is not working correctly on the webinterface ?
- could you please tell me what files I have to delete to get rid of joinserver and joinconfig
- maybe the problem is that nodered is an adapter from iobroker [(.](https://github.com/ioBroker/ioBroker.node-red) and this is the problem

any hints

**Comment by liv-in-sky** [comment]
this is the adapter

https://github.com/ioBroker/ioBroker.node-red

**Comment by joaomgcd** [comment]
Oh, you need to remove them in menu -> Configuration Nodes :)

**Comment by liv-in-sky** [comment]
ok - I won't test this because at the moment it is running

thanx again for your help
