### ISSUE TITLE
Any attempt to send a push message always errors out (but gets successfully sent)

### ISSUE THREAD

**Issue by ajayjohn** [joaomgcd/node-red-contrib-join-joaoapps#7]
The Join Node-Red module has a bug that has been there for many months now.
There is no issue in the module's ability to send out a push message, but all messages show up as failed when the node is triggered, with the following error.
[error] [join-message:<Node name>] Couldn't send push

In reality, the push message is correctly delivered. I verified this on a friends machine and his setup shows the same error too.

I couldn't find any additional related statements from the Node-Red logs, in debug mode. Just let me know if there is any further information that you'd need me to collect.

**Comment by joaomgcd** [comment]
Can you please let me know which version of the module you're using? Thanks!

**Comment by Blaradox** [comment]
I just downloaded node red a few days ago and am having a similar problem. I'm on version 1.1.1 and no matter whether or not I manually input the raspberry pi's IP address, I can't send a message to Node RED. I can however send messages from the server to any of my other devices.

There aren't any relevant debug messages on the server, but using [https://joinjoaomgcd.appspot.com/](https://joinjoaomgcd.appspot.com/) I get the response "Couldn't send command: connect timed out", but when using the Chrome Extension I get the response "Error Direct Send Failed to fetch".

Hope that helps!

**Comment by ajayjohn** [comment]
I am

**Comment by ajayjohn** [comment]
> Can you please let me know which version of the module you're using? Thanks!
I am using version 1.1.1 of the Join module, on Node-Red v0.19.5

**Comment by dgwood12** [comment]
Hate to bring up an old thread but I noticed this same bug is occurring for me right now. I'm on version 1.1.3. Join Message node errors showing "Couldn't send push" but the message still goes through.

**Comment by dgwood12** [comment]
No sooner than a minute after posting this I tried something...

I currently have the node set up with no device ID or name so it sends the message to all devices. I edited the node to use the device ID for my smartphone and tested and the message was pushed with no error. 

It appears that the issue may be that there are some devices in my device list that are unable to receive the push. This looks to be generating the "Couldn't send push" error. For some reason I have two instances of node-red in my join device list and haven't been able to figure out which one is the right one. I am thinking the one that is inactive or dead is causing this error. 

I am not sure if the error message can be redone to address this type of issue as well as the "Couldn't send push" makes it seem like the push isn't going out at all but in reality, one of my devices wasn't able to receive the push.

Hope this helps.

Thanks,

**Comment by joaomgcd** [comment]
Ah yes, that's totally it :) Normally that happens if the Windows 10 app can't receive pushes anymore. Is that maybe it?

**Comment by ajayjohn** [comment]
@joaomgcd Oddly, I don't have any Windows 10 devices in my list, only Androids and Chrome browsers.

Also, with this limitation, could you please explain how I can send a push to all Androids or all Chrome devices? If I am forced to specify a Device ID, I will only be able to send the push to a single device per node.

**Comment by joaomgcd** [comment]
If you set the id to **group.android** or **group.chrome** it should work :)
