### ISSUE TITLE
Not possible to create inbound node without Command Filter

### ISSUE THREAD

**Issue by soloam** [joaomgcd/node-red-contrib-join-joaoapps#8]
Hello, I want to pass text to my nodered without a command filter! But I must declare a command filter in nodered, and text does not enter nodered if no command is passed in the message!

Using Chrome extension to pass the information to nodered, on a different system, declaring the port, host (nodered is headless, using another server to relay messages) and with "Send Full Push" selected.

Thank You

**Comment by joaomgcd** [comment]
Hi there. What situation would need for you not to set a command filter exactly? Can you exemplify? Thanks

**Comment by soloam** [comment]
I would like to send the android notifications to my nodered. I can use AutoNotificatios to extract and send, but with the builtin join function would be cleaner.

**Comment by joaomgcd** [comment]
Then you can use a "notification" prefix and handle them in an inbound node with that command :)

**Comment by soloam** [comment]
That with tasker!? Or can join do that? Forward notifications with a prefix? 

Thank You João

**Comment by joaomgcd** [comment]
With AutoNotification you extract the info you want, then with Join you send a message (with the Send Push action) with notification=:=%antext=:=%antitle, etc... :)
