### ISSUE TITLE
Support setting values by msg payload

### ISSUE THREAD

**Issue by sriramsv** [joaomgcd/node-red-contrib-join-joaoapps#9]
Currently, it looks the node red push message doesnt set values based on msg.payload passed from the triggering node. It would be great to craft dynamic push messages if you can support them.

**Comment by joaomgcd** [comment]
Check the Advanced Push Object section [here](https://notenoughtech.com/home-automation/nodered-home-automation/how-to-use-join-app-in-nodered/).

**Comment by shanness** [comment]
Hey @joaomgcd , can I suggest you swap the order if the ||'s to `msg || push || config.`
That way, like most nodes, the config would act as a default rather than having to be either clear and set on input, or filled and ignore import.
```
	var push = msg.push || {};
...
            push.title = config.title || msg.title || push.title;
            push.url = config.url || msg.url || push.url;
            push.text =  config.text ||  msg.text || push.text;
            push.icon = config.notificationicon ||  msg.icon || push.icon;
```

**Comment by joaomgcd** [comment]
Hi there. I actually think that it makes that if someone configures something in the UI it should take prevalence to what is defined in code, because it's much more visible, so it's easier to pick up if anything is wrong.

Hope this makes sense to you.

**Comment by shanness** [comment]
Yep, fair enough, and makes sense.  Thanks
